# Generated by Django 4.0.1 on 2022-01-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(choices=[('REQ', 'Request')], default='REQ', max_length=10)),
                ('notify_to', models.CharField(max_length=50)),
                ('notify_from', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('username', models.CharField(default='null', max_length=50, primary_key=True, serialize=False)),
                ('friend', models.ManyToManyField(blank=True, to='chatapp.People')),
            ],
        ),
    ]
