# Generated by Django 4.0.1 on 2022-01-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='receive_time',
            field=models.DateTimeField(null=True),
        ),
    ]
