# Generated by Django 4.0.1 on 2022-01-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_chats_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='img',
            new_name='image',
        ),
    ]
