# Generated by Django 4.0.1 on 2022-07-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_filedata_remove_chats_image_delete_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='file_type',
            field=models.CharField(default='dd', max_length=20),
            preserve_default=False,
        ),
    ]
